package models.enums;

public enum Category {
    MEDICAMENTOS,
    INSUMOS_DESCARTABLES,
    EQUIPAMIENTO_MEDICO,
    LIMPIEZA_E_HIGIENE,
    PAPELERIA,
    REACTIVOS_Y_LABORATORIO,
    INSTRUMENTAL_QUIRURGICO,
    SERVICIOS_PROFESIONALES
}
